### PR TITLE
Fix publishing to compile with Java 8

### LINKED ISSUE #149: UnsupportedClassVersionError on JRE 8
Hello there! o/

First of all, thank you for the great work here.

I'm using the last version  `0.13.0` and I got the following exception while running on JRE 8:
`Exception in thread "main" java.lang.UnsupportedClassVersionError: com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
`

Then I downloaded the jar, extract it and check the `.class` version:
```bash
➜  opentelemetry jar xf opentelemetry-exporters-newrelic-0.13.0.jar        
➜  opentelemetry file ./com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter.class 
./com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter.class: compiled Java class data, version 55.0
```

According to `README.md`, the requirement for the building is `Java 8+`.

The question is: is `opentelemerty-exporter-java` supporting JRE 8?

My `java -version` is:
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

### PR DESCRIPTION
**Pull request by jasonjkeller**
Resolves #149 

A previous change to the `build.gradle.kts` (#128) resulted in the project being compiled by Java 11 instead of 8. This PR should fix the issue so that the exporter can run on earlier versions of Java once again.

### CODE REVIEW

**Review by XiXiaPdx — APPROVED** [review]
Confirmed with my local build, java 8.

```
  Last modified Feb 1, 2021; size 6199 bytes
  MD5 checksum 71b759365a10782fbddefd1973e69d1d
  Compiled from "NewRelicMetricExporter.java"
public class com.newrelic.telemetry.opentelemetry.export.NewRelicMetricExporter implements io.opentelemetry.sdk.metrics.export.MetricExporter
  minor version: 0
  major version: 52
```

File: opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicExporters.java [hunk 1]
```diff
@@ -55,7 +64,7 @@ public static void start(Configuration configuration) {
             .setExportIntervalMillis(configuration.collectionIntervalSeconds * 1000)
             .setMetricExporter(metricExporterBuilder.build())
             .setMetricProducers(
-                singleton(OpenTelemetrySdk.getGlobalMeterProvider().getMetricProducer()))
+                singleton(((SdkMeterProvider) GlobalMetricsProvider.get()).getMetricProducer()))
```
Comment (XiXiaPdx) [inline opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicExporters.java:67]: Is this the fix for the metric issue we investigated last week?

Comment (jasonjkeller) [reply opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicExporters.java:67]: Unfortunately It doesn't fix the issue that we were troubleshooting last week. However it does replace the deprecated `getGlobalMeterProvider` method.
